module.exports = {
  apps: [
    {
      name: 'mcq-quiz-backend',
      cwd: './backend',
      script: '/root/.nvm/versions/node/v20.11.1/bin/node',
      args: 'dist/src/index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      output: './logs/backend-out.log',
      error: './logs/backend-error.log',
      log_file: './logs/backend-combined.log',
      time: true,
      merge_logs: true,
    },
    {
      name: 'mcq-quiz-frontend',
      cwd: './frontend',
      script: 'npm',
      args: 'start',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      output: './logs/frontend-out.log',
      error: './logs/frontend-error.log',
      log_file: './logs/frontend-combined.log',
      time: true,
      merge_logs: true,
    },
  ],
};
