export const data = [
  {
    date: "18-Nov-24",
    name: "Darshit",
    email: "rohan@mail.com",
    phone: "9625002500",
    role: "MERN",
    experience: "3+",
    description: "MERN 3 years exp.",
    duration: "40min",
    status: "Not Started",
    score: "80%",
  },
  {
    date: "18-Nov-24",
    name: "Megh Patel",
    email: "viraj@mail.com",
    phone: "9625002500",
    role: "MERN",
    experience: "3+",
    description: "MERN 3 years exp.",
    duration: "40min",
    status: "Not Started",
    score: "40%",
  },
  {
    date: "18-Nov-24",
    name: "Viraj Singh",
    email: "viraj@mail.com",
    phone: "9625002500",
    role: "MERN",
    experience: "3+",
    description: "MERN 3 years exp.",
    duration: "40min",
    status: "Not Started",
    score: "60%",
  },
];

export const monthData = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"];

export const exams: Exam[] = [
  {
    date: "2024-12-17",
    task: "Frontend interview at 10 AM",
    candidate: "John Doe",
  },
  {
    date: "2024-12-17",
    task: "Backend interview at 4 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-17",
    task: "Backend interview at 6 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-20",
    task: "Backend interview at 4 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-20",
    task: "Backend interview at 9 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-20",
    task: "Backend interview at 2 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-25",
    task: "Final interview at 9 AM",
    candidate: "Alice Brown",
  },
];
export const questionsData = [
  { value: 1048, name: "React" },
  { value: 735, name: "Next.js" },
  { value: 580, name: "Typescript" },
  { value: 484, name: "Go" },
  { value: 300, name: "Ruby" },
  { value: 300, name: "Python" },
  { value: 300, name: "C/C++" },
  { value: 300, name: "Java" },
];
export const languages = ["React", "JS", "Go", "Python", "Ruby"];
export const scores = ["10", "20", "30", "40", "50", "60", "70"];
export const categories = [
  { name: "ReactJS", easy: 20, medium: 30, hard: 50 },
  { name: "NodeJS", easy: 20, medium: 30, hard: 50 },
  { name: "Python", easy: 20, medium: 30, hard: 50 },
  { name: "Vue.js", easy: 20, medium: 30, hard: 50 },
  { name: "Laravel", easy: 20, medium: 30, hard: 50 },
  { name: "PHP", easy: 20, medium: 30, hard: 50 },
];
export const candidates = [
  {
    date: "01-Nov-24",
    name: "Jane Smith",
    email: "jane.smith@mail.com",
    phone: "9587001500",
    test: "React",
    experience: "2+",
    description: "React 2 years exp.",
    duration: "30min",
    status: "Completed",
    score: "85%",
  },
  {
    date: "05-Nov-24",
    name: "Michael Brown",
    email: "michael.brown@mail.com",
    phone: "9511000500",
    test: "Node.js",
    experience: "4+",
    description: "Node.js 4 years exp.",
    duration: "50min",
    status: "Not Started",
    score: "N/A",
  },
  {
    date: "10-Nov-24",
    name: "Emily Davis",
    email: "emily.davis@mail.com",
    phone: "9522003500",
    test: "Full Stack",
    experience: "5+",
    description: "Full Stack 5 years exp.",
    duration: "1hr",
    status: "Not Started",
    score: "N/A",
  },
  {
    date: "15-Nov-24",
    name: "Chris Wilson",
    email: "chris.wilson@mail.com",
    phone: "9603004500",
    test: "JavaScript",
    experience: "1+",
    description: "JavaScript 1 year exp.",
    duration: "20min",
    status: "Completed",
    score: "75%",
  },
  {
    date: "18-Nov-24",
    name: "Sophia Johnson",
    email: "sophia.johnson@mail.com",
    phone: "9614005500",
    test: "Next.js",
    experience: "3+",
    description: "Next.js 3 years exp.",
    duration: "45min",
    status: "In Progress",
    score: "N/A",
  },
  {
    date: "01-Dec-24",
    name: "Liam White",
    email: "liam.white@mail.com",
    phone: "9708006500",
    test: "Angular",
    experience: "3+",
    description: "Angular 3 years exp.",
    duration: "40min",
    status: "Completed",
    score: "90%",
  },
  {
    date: "05-Dec-24",
    name: "Olivia Green",
    email: "olivia.green@mail.com",
    phone: "9719007500",
    test: "React Native",
    experience: "2+",
    description: "React Native 2 years exp.",
    duration: "50min",
    status: "Completed",
    score: "80%",
  },
  {
    date: "12-Dec-24",
    name: "Noah Carter",
    email: "noah.carter@mail.com",
    phone: "9723008500",
    test: "Python",
    experience: "4+",
    description: "Python 4 years exp.",
    duration: "1hr",
    status: "Not Started",
    score: "N/A",
  },
  {
    date: "20-Dec-24",
    name: "Emma Roberts",
    email: "emma.roberts@mail.com",
    phone: "9734009500",
    test: "Vue.js",
    experience: "3+",
    description: "Vue.js 3 years exp.",
    duration: "30min",
    status: "In Progress",
    score: "N/A",
  },
  {
    date: "25-Dec-24",
    name: "William Lee",
    email: "william.lee@mail.com",
    phone: "9745001500",
    test: "Django",
    experience: "5+",
    description: "Django 5 years exp.",
    duration: "1hr",
    status: "Completed",
    score: "88%",
  },
  {
    date: "25-Dec-24",
    name: "Liam White",
    email: "liam.white@mail.com",
    phone: "9708006500",
    test: "Angular",
    experience: "3+",
    description: "Angular 3 years exp.",
    duration: "40min",
    status: "Completed",
    score: "90%",
  },
  {
    date: "28-Dec-24",
    name: "Olivia Green",
    email: "olivia.green@mail.com",
    phone: "9719007500",
    test: "React Native",
    experience: "2+",
    description: "React Native 2 years exp.",
    duration: "50min",
    status: "Completed",
    score: "80%",
  },
  {
    date: "30-Dec-24",
    name: "Sophia Brown",
    email: "sophia.brown@mail.com",
    phone: "9720008500",
    test: "Vue.js",
    experience: "3+",
    description: "Vue.js 3 years exp.",
    duration: "45min",
    status: "Completed",
    score: "85%",
  },
  {
    date: "01-Jan-25",
    name: "Mason Lee",
    email: "mason.lee@mail.com",
    phone: "9731009500",
    test: "Java",
    experience: "4+",
    description: "Java 4 years exp.",
    duration: "1hr",
    status: "In Progress",
    score: "N/A",
  },
  {
    date: "02-Jan-25",
    name: "Emma Davis",
    email: "emma.davis@mail.com",
    phone: "9742010500",
    test: "React",
    experience: "2+",
    description: "React 2 years exp.",
    duration: "30min",
    status: "Completed",
    score: "88%",
  },
];

export const technologies = [
  {
    title: "MERN 3 years exp.",
    data: [
      {
        name: "MongoDB",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Express Js",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "React JS",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Node Js",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
    ],
    totalQuestions: 40,
  },
  {
    title: "Laravel 6 years exp.",
    data: [
      {
        name: "Laravel Basics",
        easy: "40%",
        medium: "40%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Eloquent ORM",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Middleware",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Blade Templates",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
    ],
    totalQuestions: 40,
  },
  {
    title: "WordPress 3-4 years exp.",
    data: [
      {
        name: "Themes",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Plugins",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Custom Fields",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Gutenberg",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
    ],
    totalQuestions: 40,
  },
];

export const AVAILABLE_CATEGORIES = ["MongoDB", "Express.Js", "React.Js", "Node.Js","Angular.Js",
  "Vue.Js",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "Python",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Go",
  "PHP",
  "Laravel",
  "Spring Boot",
  "Kotlin",
  "Swift",
  "C++",
  "C#",
  "Java",
  "Rust",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "GraphQL",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Redis",
  "Firebase",
  "AWS",
  "Azure",
  "Google Cloud",
  "SASS",
  "LESS",
  "Webpack",
  "Gulp",
  "Babel",
  "REST API",
  "Socket.IO",
  "Next.Js",
  "Nuxt.Js",
  "Redux",
  "MobX",
  "Jest",
  "Cypress",
  "Mocha",
  "Chai",
  "Tailwind CSS",
  "Material-UI",
  "Bootstrap",
  "Foundation",
  "Ant Design",
  "Electron",
  "Tauri",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "OpenCV",
  "Hadoop",
  "Spark",
  "Kafka",
  "Terraform",
  "Ansible",
  "Prometheus",
  "Grafana",
  "Splunk",
  "Elasticsearch",
  "Logstash",
  "Kibana",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "Bitbucket",
  "GitHub Actions",
  "Heroku",
  "Netlify",
  "Vercel",
  "Webpack",
  "Parcel",
  "Snowpack",
  "SolidJS",
  "Svelte",
  "Alpine.js",
  "Qwik",
  "Lit",
  "Backbone.js",
  "Ember.js",
  "Polymer",
  "Stencil",
  "Three.js",
  "Babylon.js",
  "D3.js",
  "Chart.js",
  "Highcharts",
  "CanvasJS",
  "Plotly",
  "Tableau",
  "Power BI",
  "Qlik",
  "Apache Superset",
  "Metabase",
  "Looker",
];


export const CREATE_QUESTIONS_STATIC_LIST = [
        {
            id: 1,
            type: 'multiple-choice',
            difficulty: 'easy',
            question: 'What is the primary purpose of the virtual DOM in React?',
            options: ['To store all components', 'To store all components', 'To store all components', 'To store all components'],
            correctOptions: [], // Initially no correct options selected
        },
        {
            id: 2,
            type: 'multiple-choice',
            difficulty: 'easy',
            question: 'What is the correct syntax to import React in a JavaScript file?',
            options: ['import React from react?', 'import i React from react?', 'include React from react?', 'requireReact.js'],
            correctOptions: [], // Initially no correct options selected
        },
        {
            id: 3,
            type: 'fill-in-the-blanks',
            difficulty: 'easy',
            question: 'How do you create context in React?',
            answer: 'by using React.createContext.',
        },
        {
            id: 4,
            type: 'code-snippet',
            difficulty: 'medium',
            question: 'Find the issue in it',
            code: `import React from 'react';
function App() {
  const name = ['a', 'b', 'c'];
  int i, new 'name' = ['i', 'b', 'c'];
  int j, new 'name' = ['j', 'c'];
  return i;
  const instance = items.map(item, indent) + ui;
  apply(map(items.map(i+0)));
  return end-list(instance.class);
}
export default App;`,
        },
    ]
