export const data = [
  {
    date: "18-Nov-24",
    name: "Darshit",
    email: "rohan@mail.com",
    phone: "9625002500",
    role: "MERN",
    experience: "3+",
    description: "MERN 3 years exp.",
    duration: "40min",
    status: "Not Started",
    score: "80%",
  },
  {
    date: "18-Nov-24",
    name: "Megh Patel",
    email: "viraj@mail.com",
    phone: "9625002500",
    role: "MERN",
    experience: "3+",
    description: "MERN 3 years exp.",
    duration: "40min",
    status: "Not Started",
    score: "40%",
  },
  {
    date: "18-Nov-24",
    name: "Viraj Singh",
    email: "viraj@mail.com",
    phone: "9625002500",
    role: "MERN",
    experience: "3+",
    description: "MERN 3 years exp.",
    duration: "40min",
    status: "Not Started",
    score: "60%",
  },
];

export const monthData = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"];

export const exams: Exam[] = [
  {
    date: "2024-12-17",
    task: "Frontend interview at 10 AM",
    candidate: "John Doe",
  },
  {
    date: "2024-12-17",
    task: "Backend interview at 4 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-17",
    task: "Backend interview at 6 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-20",
    task: "Backend interview at 4 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-20",
    task: "Backend interview at 9 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-20",
    task: "Backend interview at 2 PM",
    candidate: "Jane Smith",
  },
  {
    date: "2024-12-25",
    task: "Final interview at 9 AM",
    candidate: "Alice Brown",
  },
];
export const questionsData = [
  { value: 1048, name: "React" },
  { value: 735, name: "Next.js" },
  { value: 580, name: "Typescript" },
  { value: 484, name: "Go" },
  { value: 300, name: "Ruby" },
  { value: 300, name: "Python" },
  { value: 300, name: "C/C++" },
  { value: 300, name: "Java" },
];
export const languages = ["React", "JS", "Go", "Python", "Ruby"];
export const scores = ["10", "20", "30", "40", "50", "60", "70"];
export const categories = [
  { name: "ReactJS", easy: 20, medium: 30, hard: 50 },
  { name: "NodeJS", easy: 20, medium: 30, hard: 50 },
  { name: "Python", easy: 20, medium: 30, hard: 50 },
  { name: "Vue.js", easy: 20, medium: 30, hard: 50 },
  { name: "Laravel", easy: 20, medium: 30, hard: 50 },
  { name: "PHP", easy: 20, medium: 30, hard: 50 },
];


export const technologies = [
  {
    title: "MERN 3 years exp.",
    data: [
      {
        name: "MongoDB",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Express Js",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "React JS",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Node Js",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
    ],
    totalQuestions: 40,
  },
  {
    title: "Laravel 6 years exp.",
    data: [
      {
        name: "Laravel Basics",
        easy: "40%",
        medium: "40%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Eloquent ORM",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Middleware",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Blade Templates",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
    ],
    totalQuestions: 40,
  },
  {
    title: "WordPress 3-4 years exp.",
    data: [
      {
        name: "Themes",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Plugins",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Custom Fields",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
      {
        name: "Gutenberg",
        easy: "50%",
        medium: "30%",
        hard: "20%",
        questions: 10,
      },
    ],
    totalQuestions: 40,
  },
];

export const AVAILABLE_CATEGORIES = ["MongoDB", "Express.Js", "React.Js", "Node.Js","Angular.Js",
  "Vue.Js",
  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "Python",
  "Django",
  "Flask",
  "Ruby on Rails",
  "Go",
  "PHP",
  "Laravel",
  "Spring Boot",
  "Kotlin",
  "Swift",
  "C++",
  "C#",
  "Java",
  "Rust",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "GraphQL",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Redis",
  "Firebase",
  "AWS",
  "Azure",
  "Google Cloud",
  "SASS",
  "LESS",
  "Webpack",
  "Gulp",
  "Babel",
  "REST API",
  "Socket.IO",
  "Next.Js",
  "Nuxt.Js",
  "Redux",
  "MobX",
  "Jest",
  "Cypress",
  "Mocha",
  "Chai",
  "Tailwind CSS",
  "Material-UI",
  "Bootstrap",
  "Foundation",
  "Ant Design",
  "Electron",
  "Tauri",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "TensorFlow",
  "Keras",
  "PyTorch",
  "OpenCV",
  "Hadoop",
  "Spark",
  "Kafka",
  "Terraform",
  "Ansible",
  "Prometheus",
  "Grafana",
  "Splunk",
  "Elasticsearch",
  "Logstash",
  "Kibana",
  "Jenkins",
  "Travis CI",
  "CircleCI",
  "Bitbucket",
  "GitHub Actions",
  "Heroku",
  "Netlify",
  "Vercel",
  "Webpack",
  "Parcel",
  "Snowpack",
  "SolidJS",
  "Svelte",
  "Alpine.js",
  "Qwik",
  "Lit",
  "Backbone.js",
  "Ember.js",
  "Polymer",
  "Stencil",
  "Three.js",
  "Babylon.js",
  "D3.js",
  "Chart.js",
  "Highcharts",
  "CanvasJS",
  "Plotly",
  "Tableau",
  "Power BI",
  "Qlik",
  "Apache Superset",
  "Metabase",
  "Looker",
];


export const CREATE_QUESTIONS_STATIC_LIST = [
        {
            id: 1,
            type: 'multiple-choice',
            difficulty: 'easy',
            question: 'What is the primary purpose of the virtual DOM in React?',
            options: ['To store all components', 'To store all components', 'To store all components', 'To store all components'],
            correctOptions: [], // Initially no correct options selected
        },
        {
            id: 2,
            type: 'multiple-choice',
            difficulty: 'easy',
            question: 'What is the correct syntax to import React in a JavaScript file?',
            options: ['import React from react?', 'import i React from react?', 'include React from react?', 'requireReact.js'],
            correctOptions: [], // Initially no correct options selected
        },
        {
            id: 3,
            type: 'fill-in-the-blanks',
            difficulty: 'easy',
            question: 'How do you create context in React?',
            answer: 'by using React.createContext.',
        },
        {
            id: 4,
            type: 'code-snippet',
            difficulty: 'medium',
            question: 'Find the issue in it',
            code: `import React from 'react';
function App() {
  const name = ['a', 'b', 'c'];
  int i, new 'name' = ['i', 'b', 'c'];
  int j, new 'name' = ['j', 'c'];
  return i;
  const instance = items.map(item, indent) + ui;
  apply(map(items.map(i+0)));
  return end-list(instance.class);
}
export default App;`,
        },
    ]

    interface CandidateDetails {
      totalPercentage: string;
      categories: {
        [key: string]: string;
      };
      createdBy: string;
      createdOn: string;
    }
    
    interface Candidate {
      id: number;
      date: string;
      name: string;
      email: string;
      technology: string;
      experience: string;
      assessment: string;
      result: string;
      created: string;
      testStartDate: string; // New field
      testEndDate: string;   // New field
      details: CandidateDetails;
    }

   export const candidatesList: Candidate[] = [
      {
        id: 1,
        date: "18-19 Nov 2024",
        name: "Lary Page",
        email: "lary@example.com",
        technology: "MERN",
        experience: "3+",
        assessment: "MERN 3 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-11-18T09:00:00",
        testEndDate: "2024-11-18T12:00:00",
        details: {
          totalPercentage: "90%",
          categories: {
            mongodb: "20%",
            expressJs: "25%",
            reactJs: "25%",
            nodeJs: "20%",
          },
          createdBy: "Mihirbhai",
          createdOn: "17-Nov-2024 03:00PM",
        },
      },
      {
        id: 2,
        date: "18-19 Nov 2024",
        name: "Karan Doshi",
        email: "karan@example.com",
        technology: "MERN",
        experience: "3+",
        assessment: "MERN 3 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-11-18T13:00:00",
        testEndDate: "2024-11-18T16:00:00",
        details: {
          totalPercentage: "60%",
          categories: {
            mongodb: "15%",
            expressJs: "15%",
            reactJs: "15%",
            nodeJs: "15%",
          },
          createdBy: "Mihirbhai",
          createdOn: "17-Nov-2024 03:00PM",
        },
      },
      {
        id: 3,
        date: "20-21 Nov 2024",
        name: "John Doe",
        email: "john@example.com",
        technology: "Python",
        experience: "5+",
        assessment: "Python 5 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-11-20T09:00:00",
        testEndDate: "2024-11-20T12:00:00",
        details: {
          totalPercentage: "85%",
          categories: {
            python: "30%",
            django: "25%",
            flask: "20%",
            sql: "10%",
          },
          createdBy: "Mihirbhai",
          createdOn: "19-Nov-2024 10:00AM",
        },
      },
      {
        id: 4,
        date: "20-21 Nov 2024",
        name: "Jane Smith",
        email: "jane@example.com",
        technology: "Java",
        experience: "4+",
        assessment: "Java 4 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-11-20T13:00:00",
        testEndDate: "2024-11-20T16:00:00",
        details: {
          totalPercentage: "55%",
          categories: {
            java: "20%",
            spring: "15%",
            hibernate: "10%",
            sql: "10%",
          },
          createdBy: "Mihirbhai",
          createdOn: "19-Nov-2024 11:00AM",
        },
      },
      {
        id: 5,
        date: "22-23 Nov 2024",
        name: "Alice Johnson",
        email: "alice@example.com",
        technology: "MEAN",
        experience: "2+",
        assessment: "MEAN 2 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-11-22T09:00:00",
        testEndDate: "2024-11-22T12:00:00",
        details: {
          totalPercentage: "80%",
          categories: {
            mongodb: "20%",
            expressJs: "20%",
            angular: "20%",
            nodeJs: "20%",
          },
          createdBy: "Mihirbhai",
          createdOn: "21-Nov-2024 02:00PM",
        },
      },
      {
        id: 6,
        date: "22-23 Nov 2024",
        name: "Bob Brown",
        email: "bob@example.com",
        technology: "MEAN",
        experience: "2+",
        assessment: "MEAN 2 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-11-22T13:00:00",
        testEndDate: "2024-11-22T16:00:00",
        details: {
          totalPercentage: "50%",
          categories: {
            mongodb: "10%",
            expressJs: "10%",
            angular: "10%",
            nodeJs: "20%",
          },
          createdBy: "Mihirbhai",
          createdOn: "21-Nov-2024 03:00PM",
        },
      },
      {
        id: 7,
        date: "24-25 Nov 2024",
        name: "Charlie Davis",
        email: "charlie@example.com",
        technology: "React Native",
        experience: "3+",
        assessment: "React Native 3 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-11-24T09:00:00",
        testEndDate: "2024-11-24T12:00:00",
        details: {
          totalPercentage: "88%",
          categories: {
            javascript: "30%",
            reactNative: "30%",
            redux: "20%",
            firebase: "8%",
          },
          createdBy: "Mihirbhai",
          createdOn: "23-Nov-2024 09:00AM",
        },
      },
      {
        id: 8,
        date: "24-25 Nov 2024",
        name: "Eva Green",
        email: "eva@example.com",
        technology: "React Native",
        experience: "3+",
        assessment: "React Native 3 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-11-24T13:00:00",
        testEndDate: "2024-11-24T16:00:00",
        details: {
          totalPercentage: "45%",
          categories: {
            javascript: "15%",
            reactNative: "15%",
            redux: "10%",
            firebase: "5%",
          },
          createdBy: "Mihirbhai",
          createdOn: "23-Nov-2024 10:00AM",
        },
      },
      {
        id: 9,
        date: "26-27 Nov 2024",
        name: "Frank White",
        email: "frank@example.com",
        technology: "MERN",
        experience: "3+",
        assessment: "MERN 3 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-11-26T09:00:00",
        testEndDate: "2024-11-26T12:00:00",
        details: {
          totalPercentage: "92%",
          categories: {
            mongodb: "25%",
            expressJs: "25%",
            reactJs: "25%",
            nodeJs: "17%",
          },
          createdBy: "Mihirbhai",
          createdOn: "25-Nov-2024 09:00AM",
        },
      },
      {
        id: 10,
        date: "26-27 Nov 2024",
        name: "Grace Lee",
        email: "grace@example.com",
        technology: "Python",
        experience: "5+",
        assessment: "Python 5 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-11-26T13:00:00",
        testEndDate: "2024-11-26T16:00:00",
        details: {
          totalPercentage: "58%",
          categories: {
            python: "20%",
            django: "15%",
            flask: "15%",
            sql: "8%",
          },
          createdBy: "Mihirbhai",
          createdOn: "25-Nov-2024 10:00AM",
        },
      },
      {
        id: 11,
        date: "28-29 Nov 2024",
        name: "Henry Brown",
        email: "henry@example.com",
        technology: "Java",
        experience: "4+",
        assessment: "Java 4 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-11-28T09:00:00",
        testEndDate: "2024-11-28T12:00:00",
        details: {
          totalPercentage: "87%",
          categories: {
            java: "30%",
            spring: "25%",
            hibernate: "20%",
            sql: "12%",
          },
          createdBy: "Mihirbhai",
          createdOn: "27-Nov-2024 09:00AM",
        },
      },
      {
        id: 12,
        date: "28-29 Nov 2024",
        name: "Ivy Taylor",
        email: "ivy@example.com",
        technology: "MEAN",
        experience: "2+",
        assessment: "MEAN 2 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-11-28T13:00:00",
        testEndDate: "2024-11-28T16:00:00",
        details: {
          totalPercentage: "52%",
          categories: {
            mongodb: "15%",
            expressJs: "15%",
            angular: "15%",
            nodeJs: "7%",
          },
          createdBy: "Mihirbhai",
          createdOn: "27-Nov-2024 10:00AM",
        },
      },
      {
        id: 13,
        date: "30 Nov - 1 Dec 2024",
        name: "Jack Wilson",
        email: "jack@example.com",
        technology: "React Native",
        experience: "3+",
        assessment: "React Native 3 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-11-30T09:00:00",
        testEndDate: "2024-11-30T12:00:00",
        details: {
          totalPercentage: "89%",
          categories: {
            javascript: "30%",
            reactNative: "30%",
            redux: "20%",
            firebase: "9%",
          },
          createdBy: "Mihirbhai",
          createdOn: "29-Nov-2024 09:00AM",
        },
      },
      {
        id: 14,
        date: "30 Nov - 1 Dec 2024",
        name: "Karen Harris",
        email: "karen@example.com",
        technology: "MERN",
        experience: "3+",
        assessment: "MERN 3 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-11-30T13:00:00",
        testEndDate: "2024-11-30T16:00:00",
        details: {
          totalPercentage: "48%",
          categories: {
            mongodb: "10%",
            expressJs: "10%",
            reactJs: "10%",
            nodeJs: "18%",
          },
          createdBy: "Mihirbhai",
          createdOn: "29-Nov-2024 10:00AM",
        },
      },
      {
        id: 15,
        date: "2-3 Dec 2024",
        name: "Leo Martinez",
        email: "leo@example.com",
        technology: "Python",
        experience: "5+",
        assessment: "Python 5 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-12-02T09:00:00",
        testEndDate: "2024-12-02T12:00:00",
        details: {
          totalPercentage: "91%",
          categories: {
            python: "35%",
            django: "25%",
            flask: "20%",
            sql: "11%",
          },
          createdBy: "Mihirbhai",
          createdOn: "1-Dec-2024 09:00AM",
        },
      },
      {
        id: 16,
        date: "2-3 Dec 2024",
        name: "Mia Clark",
        email: "mia@example.com",
        technology: "Java",
        experience: "4+",
        assessment: "Java 4 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-12-02T13:00:00",
        testEndDate: "2024-12-02T16:00:00",
        details: {
          totalPercentage: "53%",
          categories: {
            java: "20%",
            spring: "15%",
            hibernate: "10%",
            sql: "8%",
          },
          createdBy: "Mihirbhai",
          createdOn: "1-Dec-2024 10:00AM",
        },
      },
      {
        id: 17,
        date: "4-5 Dec 2024",
        name: "Noah Lewis",
        email: "noah@example.com",
        technology: "MEAN",
        experience: "2+",
        assessment: "MEAN 2 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-12-04T09:00:00",
        testEndDate: "2024-12-04T12:00:00",
        details: {
          totalPercentage: "84%",
          categories: {
            mongodb: "25%",
            expressJs: "25%",
            angular: "20%",
            nodeJs: "14%",
          },
          createdBy: "Mihirbhai",
          createdOn: "3-Dec-2024 09:00AM",
        },
      },
      {
        id: 18,
        date: "4-5 Dec 2024",
        name: "Olivia Walker",
        email: "olivia@example.com",
        technology: "React Native",
        experience: "3+",
        assessment: "React Native 3 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-12-04T13:00:00",
        testEndDate: "2024-12-04T16:00:00",
        details: {
          totalPercentage: "47%",
          categories: {
            javascript: "15%",
            reactNative: "15%",
            redux: "10%",
            firebase: "7%",
          },
          createdBy: "Mihirbhai",
          createdOn: "3-Dec-2024 10:00AM",
        },
      },
      {
        id: 19,
        date: "6-7 Dec 2024",
        name: "Paul Hall",
        email: "paul@example.com",
        technology: "MERN",
        experience: "3+",
        assessment: "MERN 3 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-12-06T09:00:00",
        testEndDate: "2024-12-06T12:00:00",
        details: {
          totalPercentage: "93%",
          categories: {
            mongodb: "30%",
            expressJs: "25%",
            reactJs: "25%",
            nodeJs: "13%",
          },
          createdBy: "Mihirbhai",
          createdOn: "5-Dec-2024 09:00AM",
        },
      },
      {
        id: 20,
        date: "6-7 Dec 2024",
        name: "Quinn Young",
        email: "quinn@example.com",
        technology: "Python",
        experience: "5+",
        assessment: "Python 5 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-12-06T13:00:00",
        testEndDate: "2024-12-06T16:00:00",
        details: {
          totalPercentage: "57%",
          categories: {
            python: "20%",
            django: "15%",
            flask: "15%",
            sql: "7%",
          },
          createdBy: "Mihirbhai",
          createdOn: "5-Dec-2024 10:00AM",
        },
      },
      {
        id: 21,
        date: "8-9 Dec 2024",
        name: "Ryan Allen",
        email: "ryan@example.com",
        technology: "Java",
        experience: "4+",
        assessment: "Java 4 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-12-08T09:00:00",
        testEndDate: "2024-12-08T12:00:00",
        details: {
          totalPercentage: "88%",
          categories: {
            java: "30%",
            spring: "25%",
            hibernate: "20%",
            sql: "13%",
          },
          createdBy: "Mihirbhai",
          createdOn: "7-Dec-2024 09:00AM",
        },
      },
      {
        id: 22,
        date: "8-9 Dec 2024",
        name: "Sara King",
        email: "sara@example.com",
        technology: "MEAN",
        experience: "2+",
        assessment: "MEAN 2 years exp.",
        result: "Fail",
        created: "Mihirbhai",
        testStartDate: "2024-12-08T13:00:00",
        testEndDate: "2024-12-08T16:00:00",
        details: {
          totalPercentage: "49%",
          categories: {
            mongodb: "15%",
            expressJs: "15%",
            angular: "15%",
            nodeJs: "4%",
          },
          createdBy: "Mihirbhai",
          createdOn: "7-Dec-2024 10:00AM",
        },
      },
      {
        id: 23,
        date: "10-11 Dec 2024",
        name: "Tom Wright",
        email: "tom@example.com",
        technology: "React Native",
        experience: "3+",
        assessment: "React Native 3 years exp.",
        result: "Pass",
        created: "Mihirbhai",
        testStartDate: "2024-12-10T09:00:00",
        testEndDate: "2024-12-10T12:00:00",
        details: {
          totalPercentage: "90%",
          categories: {
            javascript: "30%",
            reactNative: "30%",
            redux: "20%",
            firebase: "10%",
          },
          createdBy: "Mihirbhai",
          createdOn: "9-Dec-2024 09:00AM",
        },
      },
      
    ];
